### ISSUE TITLE
Fail to run the example 'graphicstest_featherwing'

### ISSUE THREAD

**Issue by zackhaikal** [adafruit/Adafruit_ILI9341#20]
'TFT_CS' was not declared in this scope
I got the above statement when trying to compile graphicstest_featherwing.ino
I reviewed the code and found that TFT_CS is already declared
There's something that I missed?
I'm using Arduino 1.6.12 in Windows 7

**Comment by ladyada** [comment]
what are you using

**Comment by zackhaikal** [comment]
@ladyada Arduino Uno R3

**Comment by ladyada** [comment]
please contact lelong for support and help :)
