### ISSUE TITLE
Error compliling :'TFT_CS' was not declared in this scope

### ISSUE THREAD

**Issue by lostgab** [adafruit/Adafruit_ILI9341#22]
this is the error i got after uploading the graphictest featherwing

graphicstest_featherwing:50: error: 'TFT_CS' was not declared in this scope

 Adafruit_ILI9341 tft = Adafruit_ILI9341(TFT_CS, TFT_DC);

                                         ^

graphicstest_featherwing:50: error: 'TFT_DC' was not declared in this scope

 Adafruit_ILI9341 tft = Adafruit_ILI9341(TFT_CS, TFT_DC);

**Comment by ladyada** [comment]
you have to select the right feather board in arduino
