### ISSUE TITLE
Regarding RST pin option

### ISSUE THREAD

**Issue by ecaits** [adafruit/Adafruit_ILI9341#23]
Hello,

As you have written in readme.txt file that these displays use SPI to communicate, 4 or 5 pins are required to interface (RST is optional). During testing of program code, I have found that if I remove the RST pin then the screen become white. 
How can I make RST pin optional. Actually, I do not want to use it during interfacing to reduce the number of pin of arduino ethernet board.

Thanks in advance.

**Comment by ladyada** [comment]
tech support for adafruit products is handled in the forums.

**Comment by ecaits** [comment]
Please provide me the link for forum where I can discuss and can get the solution.
