### ISSUE TITLE
Query related to speed

### ISSUE THREAD

**Issue by stanzlavos** [adafruit/Adafruit_ILI9341#24]
Hi

This post is more of a query and not an "issue". :)

I am driving a 240x320 display with the ILI9341 using a NodeMCU ESP8266. I am trying to display a full screen BMP and measure the time taken. 

* ESP8266 running at 160Mhz
* SPI freq at 40000000
* I was using the the library version 1.0.2. But then I saw a commit with the following change : 

```
#if defined (__AVR__) || defined(TEENSYDUINO) || defined (__arm__) || **defined (ESP8266)**
#define USE_FAST_PINIO
#endif
```

So, I moved to that version.

I had to tweak a lot of code here and there to get it to work.

1) Made a small binary to make a HEX dump of the BMP.
2) Made an array in PROGMEM using the hex dump.
3) Modified a drawBMP sample code I found to use the array instead of reading from SD card.

The time taken to draw the image is around 534ms. Now my question is : 

Is it possible to draw any faster ? I did see many "optimized" version online, but could not find one that worked for the ESP8266.

**Comment by ladyada** [comment]
you can optimize more and more but at some point it becomes challenging to support.
