### ISSUE TITLE
ESP8266 Bitmap not showing.

### ISSUE THREAD

**Issue by ran6110** [adafruit/Adafruit_ILI9341#27]
The move from 1.0.2 to 1.0.3 appears to cause bitmaps to no longer be displayed when using the  Huzzah ESP8266.

I did a diff between the versions and there appears to be significant changes including removal of ESP8266 defined sections.

Is this a permanent change to remove the ESP8266 from the supported devices in favor of the ESP32? If so then there needs to be a branch so the EPS8266 users don't keep retrieving code that won't work.

![img_2477](https://cloud.githubusercontent.com/assets/1048318/24333356/1a807512-120b-11e7-8133-42747480e252.JPG)

**Comment by PaintYourDragon** [comment]
Problem was in weather sketch, not library. Fixed, explanation in forums.
