### ISSUE TITLE
Is USE_FAST_GPIO working for Feather nRF52 as a __arm__ platform?

### ISSUE THREAD

**Issue by prjh** [adafruit/Adafruit_ILI9341#28]
I have tested this library for the Nordic nRF52-DK board with Sandeep Mistry's [arduino-nRF5 ](https://github.com/sandeepmistry/arduino-nRF5) board implementation. I got it working by inhibiting USE_FAST_GPIO for the Nordic NRF52-DK board as it is a `__arm__ `platform. 
Doing like that:
```
#if defined (__AVR__) || defined(TEENSYDUINO) || defined(ESP8266) || defined (ESP32) || defined(__arm__)
#if !defined(NRF5)
#define USE_FAST_PINIO
#endif
#endif

```
Did it really work with the new Feather nRF52 - also based on` __arm__ `?

**Comment by ladyada** [comment]
hiya this is old but i think its resolved now because all optimizations are done in SPITFT!
