### ISSUE TITLE
Initialization code in Adafruit_ILI9341.cpp sends 7 undocumented commands

### ISSUE THREAD

**Issue by psyklopz** [adafruit/Adafruit_ILI9341#31]
In Adafruit_ILI9341.cpp, from lines 271 to 305, (in the begin() method) sends a series of 7 undocumented commands over the SPI bus.  The commands are not included in the ILI9341 datasheet, and so they must be ignored by the controller?

Commenting them out has no effect from what I can tell.  I'm testing this with the 2.8" display, capacitive touch.  Maybe these are left over garbage from the other resistive touch display?  That touch screen was on the SPI bus.

I suggest either removing the extra lines, or adding a code comment indicating their purpose.  It would be nice to #define the magic numbers, that would have helped me understand their intent.

**Comment by ladyada** [comment]
its standard for there to be custom commands per TFT - they were given to us by the TFT manufacturer. they cause no harm, so they can stay. thanks! :)
