### ISSUE TITLE
Move SPI macros to header file to make them reusable?

### ISSUE THREAD

**Issue by PaulChristopher** [adafruit/Adafruit_ILI9341#40]
I like the abtraction layers for hardware/software SPI and different MCUs. I'm wondering if these macros in Adafruit_ILI9341.cpp line 68-201 could be moved to Adafruit_ILI9341.h? By doing this, these great macros could be easily reused in other platform independet, more generic libraries/classes when needing to interface with other SPI devices like touch? (I.e. I could simply include Adafruit_ILI9341.h there and work with the given SPI macros abstracting from MCU and hardware/software SPI).

**Comment by ladyada** [comment]
hiya we're moving to abstracting away SPI TFT to adafruit GFX and shoving all the optimizations there, see the spitft branch we recently pushed to!
