### ISSUE TITLE
Example code will not compile with latest changes to Adafruit-GFX-Library

### ISSUE THREAD

**Issue by ardnew** [adafruit/Adafruit_ILI9341#45]
- Arduino board: Adafruit PyPortal M4 (SAMD51)
- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.9
- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): Simply follow the [Arduino setup guide for PyPortal](https://learn.adafruit.com/adafruit-pyportal/setup) and try compiling the [self-test sketch](https://learn.adafruit.com/adafruit-pyportal/arduino-test)

see the most recent commit to the `Adafruit-GFX-Library`: [`1b03380`](https://github.com/adafruit/Adafruit-GFX-Library/commit/1b033808ab61fdc221f39c2257a565d2bb9b823f)

the `tftBusWidth` enum value `tft8` was changed to `tft8bitbus` because class `Adafruit_SPITFT` had a protected anon union containing a named member struct with the same name. 

to  fix this, it probably would have been safer changing the _union member's name_ instead of the enum, since the union is protected and the enum was visible externally. but as-is, the examples for this library need to update their `tft8` references to `tft8bitbus`. otherwise, currently, none of the following examples will compile: 
[`graphicstest_pyportal`](https://github.com/adafruit/Adafruit_ILI9341/tree/master/examples/graphicstest_pyportal)
[`pyportal_boing`](https://github.com/adafruit/Adafruit_ILI9341/tree/master/examples/pyportal_boing)
[`touchpaint_pyportal`](https://github.com/adafruit/Adafruit_ILI9341/tree/master/examples/touchpaint_pyportal)
[`mandelbrot`](https://github.com/adafruit/Adafruit_ILI9341/tree/master/examples/mandelbrot)

also the example in `Adafruit_ImageReader_Library`:
[`PyPortal`](https://github.com/adafruit/Adafruit_ImageReader/tree/master/examples/PyPortal)

**Comment by ladyada** [comment]
thanks - well, i fixed it the most obvious way i could while making it clear - could you submit a PR for fixes of these examples? that would be rad and if travis passes, we'll merge!

**Comment by ladyada** [comment]
thanks :)
