### ISSUE TITLE
Error while compiling example code

### ISSUE THREAD

**Issue by akshulg** [adafruit/Adafruit_ILI9341#48]
In file included from /home/username/Arduino/libraries/Adafruit_ILI9341/examples/graphicstest/graphicstest.ino:19:0:
/home/username/Arduino/libraries/Adafruit_ILI9341/Adafruit_ILI9341.h:140:38: error: expected ')' before 'busWidth'
         Adafruit_ILI9341(tftBusWidth busWidth, int8_t d0, int8_t wr, int8_t dc,
                                      ^

**Comment by caternuson** [comment]
Make sure you have the latest version of both this library and the GFX library:
https://github.com/adafruit/Adafruit-GFX-Library

**Comment by akshulg** [comment]
Thanks, that was the issue
