### ISSUE TITLE
overwrite text

### ISSUE THREAD

**Issue by avandalen** [adafruit/Adafruit_ILI9341#58]
I have made an extension for overwriting numbers. See here:
How to overwrite text to the Arduino ILI9341 display:
https://www.avdweb.nl/arduino/hardware-interfacing/ili9341-tft
You can integrate it into your library if you want.

**Comment by ladyada** [comment]
hiya a PR to SPITFT (in Adafruit_GFX) would be the best way to get it included! we cannot use code that is under a "CC Non Commercial" license

**Comment by avandalen** [comment]
Hi

I changed all my software to MIT licence now

what do you with
hiya a PR to SPITFT 

Kind regards 
Albert

**Comment by caternuson** [comment]
@avandalen In general:
* Fork the Adafruit_GFX repo: <https://github.com/adafruit/Adafruit-GFX-Library>
* Make a branch
* Add your code to the branch
* PR that branch back to the Adafruit_GFX repo

More info in this guide:
https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github/overview

**Comment by avandalen** [comment]
I accidentally verified my own branch (GPX.cpp and GPX.h), can you undo this?

**Comment by avandalen** [comment]
Ingnore this previous comment: I accidentally verified my own branch (GPX.cpp and GPX.h), can you undo this?
