### ISSUE TITLE
rst logic broken for arm

### ISSUE THREAD

**Issue by manitou48** [adafruit/Adafruit_ILI9341#6]
For arm rst pin is declared unsigned, so  " if (_rst <0) ... " stuff is broken.  Probably need to use unsigned for avr too, and preset/test with 255

Could add additional conditionals for Arduino ZERO vs DUE

**Comment by tdicola** [comment]
Thanks for catching the issue!  Just fixed it by making the pin numbers signed ints and tested with an Arduino Zero.
