### ISSUE TITLE
ILI9341V compatibility

### ISSUE THREAD

**Issue by renno-bih** [adafruit/Adafruit_ILI9341#61]
Hi,
I plan to use 2.4" display with ILI9341V controller. But I cannot find any information if ILI9341V is back-compatible with ILI9341. Only information I can find is that **V** is improved version of ILI9341.
ILI9341V that I plan to use can be configured to use different interfaces. 
Confusing thing is that datasheet mentions two types of 4-wire interface:

- 4-wire 8-bit data serial interface Ⅰ (SCL,SDA,D/CX,CSX)
- 4-wire 8-bit data serial interface Ⅱ (SCL,SDI,D/CX,SDO, CSX )

Will it be possible to use ILI9341V with this library and what interface to configure in order to be compatible with this library?

**Comment by ladyada** [comment]
no idea - you could try it. if it doesn't work please contact the vendor of the screen for advice, they can give you init code that you'd have to write to make it work :) if you get it working, please submit a PR!
