### ISSUE TITLE
tamplates based design

### ISSUE THREAD

**Issue by ag88** [adafruit/Adafruit_ILI9341#69]
hi would Adafruit consider making a c++ template based design for this?
a reason is that as the 'platforms' get more varied it adds more code bloat as each 'platform' (mcu/boards) is added
e.g. platforms that supports hardware SPI probably won't need software SPI and that code is simply unused but built and compiled into the binaries.

common codes (e.g. the public, protected (callback) api parts) can go into the template, so that each different 'platform' (hard spi, soft spi, mcu, board etc) is perhaps a different class

**Comment by ladyada** [comment]
we already do, its called Adafruit_GFX
uncalled code is not compiled in - your compiler does all these things for you
