### ISSUE TITLE
Arduino ILI9341 simulation 😀

### ISSUE THREAD

**Issue by matititam** [adafruit/Adafruit_ILI9341#74]
Dear Team,

Good day

We are ever grateful for such wonderful libraries. I have here a permanent link for the simulation.  
https://wokwi.com/arduino/projects/307567275170333248

It would be awesome if you can make this link available to the future readers.
We will be excited to hear about the feedback on the simulator as well. May we know, how we can make it better to publish such useful libraries in the future. 

Thank you!
Matititam

![image](https://user-images.githubusercontent.com/68117142/134281567-78b9e947-767e-4b41-8f8f-1d993ae64c6d.png)

**Comment by makermelissa** [comment]
Hi, I just got around to trying this out. That's pretty awesome. What did you have in mind for sharing the link?

**Comment by m-bob** [comment]
Astonishing work: thank you! Seriously impressive. After watching the simulation, I visited your www.wokwi.com site and your GitHub site https://github.com/wokwi .

I also found your "club" site https://wokwi.com/club . I haven't (yet) joined, but I expect I will.

Do you have any plans to release local versions of your codes which wouldn't require web connectivity?

**Comment by makermelissa** [comment]
Closing this issue for now since I'm not sure what to do with it.
