### ISSUE TITLE
Display Hindi Language font/Text on TFT 

### ISSUE THREAD

**Issue by nvgadhiya** [adafruit/Adafruit_ILI9341#78]
I want to display Hindi language font/Text on TFT ILI9341. I am using Arduino Mega board.
Should I change library or anything else? How can I develop new font/ Hindi language font?
How can I display it? Please support.

**Comment by ladyada** [comment]
we do not support it at this time

**Comment by nvgadhiya** [comment]
> we do not support it at this time

Any Technical solution available for this?
