### ISSUE TITLE
ESP8266 support

### ISSUE THREAD

**Issue by lunanigra** [adafruit/Adafruit_ILI9341#8]
Hello, is the Adafruit ILI9341 lib already compatible to ESP8266?

**Comment by lunanigra** [comment]
Ok, seems the ESP8266 Arduino IDE already provides a modified lib... So, please just add a comment to the readme.

**Comment by hb020** [comment]
Now that is no longer true. It was in staging, and did not make it in the 2.0 version. The version WAS in the arduino IDE git repo is here: https://github.com/Links2004/Adafruit_ILI9341 (and in sandeep's fork of the IDE)
And it is worth it. Fast, and complete (as far as I can tell). Can you please merge?

**Comment by grahamehorner** [comment]
...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In constructor 'Adafruit_ILI9341::Adafruit_ILI9341(int8_t, int8_t, int8_t, int8_t, int8_t, int8_t)':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:30:3: error: '_cs' was not declared in this scope

   _cs   = cs;

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:31:3: error: '_dc' was not declared in this scope

   _dc   = dc;

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:32:3: error: '_mosi' was not declared in this scope

   _mosi  = mosi;

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:33:3: error: '_miso' was not declared in this scope

   _miso = miso;

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:34:3: error: '_sclk' was not declared in this scope

   _sclk = sclk;

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:35:3: error: '_rst' was not declared in this scope

   _rst  = rst;

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In constructor 'Adafruit_ILI9341::Adafruit_ILI9341(int8_t, int8_t, int8_t)':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:43:3: error: '_cs' was not declared in this scope

   _cs   = cs;

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:44:3: error: '_dc' was not declared in this scope

   _dc   = dc;

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:45:3: error: '_rst' was not declared in this scope

   _rst  = rst;

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:47:3: error: '_mosi' was not declared in this scope

   _mosi  = _sclk = 0;

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:47:12: error: '_sclk' was not declared in this scope

   _mosi  = _sclk = 0;

            ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In member function 'void Adafruit_ILI9341::spiwrite(uint8_t)':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:74:3: error: 'mosiport' was not declared in this scope

  *mosiport |=  mosipinmask;

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:74:16: error: 'mosipinmask' was not declared in this scope

  *mosiport |=  mosipinmask;

                ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:77:3: error: 'mosiport' was not declared in this scope

  *mosiport &= ~mosipinmask;

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:77:16: error: 'mosipinmask' was not declared in this scope

  *mosiport &= ~mosipinmask;

                ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:80:8: error: 'clkport' was not declared in this scope

       *clkport |=  clkpinmask;

        ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:80:20: error: 'clkpinmask' was not declared in this scope

       *clkport |=  clkpinmask;

                    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In member function 'void Adafruit_ILI9341::writecommand(uint8_t)':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:89:4: error: 'dcport' was not declared in this scope

   *dcport &=  ~dcpinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:89:16: error: 'dcpinmask' was not declared in this scope

   *dcport &=  ~dcpinmask;

                ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:93:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:93:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In member function 'void Adafruit_ILI9341::writedata(uint8_t)':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:104:4: error: 'dcport' was not declared in this scope

   *dcport |=  dcpinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:104:15: error: 'dcpinmask' was not declared in this scope

   *dcport |=  dcpinmask;

               ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:108:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:108:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In member function 'void Adafruit_ILI9341::begin()':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:169:7: error: '_rst' was not declared in this scope

   if (_rst > 0) {

       ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:174:11: error: '_dc' was not declared in this scope

   pinMode(_dc, OUTPUT);

           ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:175:11: error: '_cs' was not declared in this scope

   pinMode(_cs, OUTPUT);

           ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:176:3: error: 'csport' was not declared in this scope

   csport    = portOutputRegister(digitalPinToPort(_cs));

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:177:3: error: 'cspinmask' was not declared in this scope

   cspinmask = digitalPinToBitMask(_cs);

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:178:3: error: 'dcport' was not declared in this scope

   dcport    = portOutputRegister(digitalPinToPort(_dc));

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:179:3: error: 'dcpinmask' was not declared in this scope

   dcpinmask = digitalPinToBitMask(_dc);

   ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:200:13: error: '_sclk' was not declared in this scope

     pinMode(_sclk, OUTPUT);

             ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:201:13: error: '_mosi' was not declared in this scope

     pinMode(_mosi, OUTPUT);

             ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:202:13: error: '_miso' was not declared in this scope

     pinMode(_miso, INPUT);

             ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:203:5: error: 'clkport' was not declared in this scope

     clkport     = portOutputRegister(digitalPinToPort(_sclk));

     ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:204:5: error: 'clkpinmask' was not declared in this scope

     clkpinmask  = digitalPinToBitMask(_sclk);

     ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:205:5: error: 'mosiport' was not declared in this scope

     mosiport    = portOutputRegister(digitalPinToPort(_mosi));

     ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:206:5: error: 'mosipinmask' was not declared in this scope

     mosipinmask = digitalPinToBitMask(_mosi);

     ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:212:7: error: '_rst' was not declared in this scope

   if (_rst > 0) {

       ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In member function 'void Adafruit_ILI9341::pushColor(uint16_t)':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:371:4: error: 'dcport' was not declared in this scope

   *dcport |=  dcpinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:371:15: error: 'dcpinmask' was not declared in this scope

   *dcport |=  dcpinmask;

               ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:373:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:373:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In member function 'virtual void Adafruit_ILI9341::drawPixel(int16_t, int16_t, uint16_t)':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:391:4: error: 'dcport' was not declared in this scope

   *dcport |=  dcpinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:391:15: error: 'dcpinmask' was not declared in this scope

   *dcport |=  dcpinmask;

               ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:393:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:393:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In member function 'virtual void Adafruit_ILI9341::drawFastVLine(int16_t, int16_t, int16_t, uint16_t)':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:418:4: error: 'dcport' was not declared in this scope

   *dcport |=  dcpinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:418:15: error: 'dcpinmask' was not declared in this scope

   *dcport |=  dcpinmask;

               ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:420:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:420:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In member function 'virtual void Adafruit_ILI9341::drawFastHLine(int16_t, int16_t, int16_t, uint16_t)':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:443:4: error: 'dcport' was not declared in this scope

   *dcport |=  dcpinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:443:15: error: 'dcpinmask' was not declared in this scope

   *dcport |=  dcpinmask;

               ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:444:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:444:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In member function 'virtual void Adafruit_ILI9341::fillRect(int16_t, int16_t, int16_t, int16_t, uint16_t)':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:474:4: error: 'dcport' was not declared in this scope

   *dcport |=  dcpinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:474:15: error: 'dcpinmask' was not declared in this scope

   *dcport |=  dcpinmask;

               ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:476:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:476:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In member function 'uint8_t Adafruit_ILI9341::spiread()':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:568:20: error: '_sclk' was not declared in this scope

       digitalWrite(_sclk, LOW);

                    ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:571:23: error: '_miso' was not declared in this scope

       if (digitalRead(_miso))

                       ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In member function 'uint8_t Adafruit_ILI9341::readdata()':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:581:17: error: '_dc' was not declared in this scope

    digitalWrite(_dc, HIGH);

                 ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:582:17: error: '_cs' was not declared in this scope

    digitalWrite(_cs, LOW);

                 ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In member function 'uint8_t Adafruit_ILI9341::readcommand8(uint8_t, uint8_t)':

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:592:17: error: '_dc' was not declared in this scope

    digitalWrite(_dc, LOW); // command

                 ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:593:17: error: '_cs' was not declared in this scope

    digitalWrite(_cs, LOW);

                 ^

...\Adafruit_ILI9341\Adafruit_ILI9341.cpp:600:17: error: '_sclk' was not declared in this scope

    digitalWrite(_sclk, LOW);

                 ^

**Comment by ladyada** [comment]
added in 
https://github.com/adafruit/Adafruit_ILI9341/commit/08167ad8740c5a4a43f771d539aa7886f5100719
use the default SPI pins SCK #14, MOSI #13, MISO #12 and CS #4, DC #5

**Comment by alkhimey** [comment]
It seems that the latest commit have broken it again.

**Comment by ladyada** [comment]
woops you're right. fixed!

**Comment by rahulmr999** [comment]
I have some issues using the mentioned adafruit library and the ESP8266 arduino. I made the connections as mentioned 

> default SPI pins SCK #14, MOSI #13, MISO #12 and CS #4, DC #5.

The display works for a few seconds for the graphicsTest example. but the line test starts, it gets stuck and ESP reboots. Even when used in my project just to show some text, it reboots after a few successful attempts. 

I am using the 2.2 TFT ILI9341 LCD and ESPressoLite 1 which uses ESPWROOM 02

**Comment by ladyada** [comment]
rahulmr999 this is not the place for tech support - contact the seller of your ESP module for support!
